# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI
on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: artifactoryPublish
          gradle-version: 8.5

      - uses: actions/upload-artifact@v2
        with:
          name: api
          path: build/libs